version: '3.9'

services:
  prestashop:
    image: prestashop/prestashop:8.2
    container_name: prestashop
    environment:
      - DB_SERVER=${DB_SERVER}           # Database server from Coolify
      - DB_NAME=${DB_NAME}               # Database name from Coolify
      - DB_USER=${DB_USER}               # Database user from Coolify
      - DB_PASSWORD=${DB_PASSWORD}       # Database password from Coolify
      - PS_INSTALL_AUTO=0                # Disable automatic installation
    volumes:
      - prestashop_data:/var/www/html    # Persistent PrestaShop data
      - ./:/repo:ro                      # Mount the repository root
    entrypoint: ["/repo/entrypoint.sh"]  # Custom entrypoint
    networks:
      - ${NETWORK_NAME}                  # Dynamically set network from Coolify

networks:
  default:                               # Define the default network for fallback
    driver: bridge

volumes:
  prestashop_data:
